# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hr_arma_fit_cpp <- function(y_in, p, q, p_big = 0L, iter = 0L) {
    .Call(`_fmriAR_hr_arma_fit_cpp`, y_in, p, q, p_big, iter)
}

parcel_means_cpp <- function(resid, parcels, K = -1L, na_rm = FALSE) {
    .Call(`_fmriAR_parcel_means_cpp`, resid, parcels, K, na_rm)
}

run_avg_acvf_cpp <- function(mat, max_lag) {
    .Call(`_fmriAR_run_avg_acvf_cpp`, mat, max_lag)
}

segmented_acvf_cpp <- function(y, run_starts, max_lag, unbiased = FALSE, center = TRUE) {
    .Call(`_fmriAR_segmented_acvf_cpp`, y, run_starts, max_lag, unbiased, center)
}

yw_from_acvf_cpp <- function(gamma, p) {
    .Call(`_fmriAR_yw_from_acvf_cpp`, gamma, p)
}

arma_whiten_inplace <- function(Y, X, phi, theta, run_starts, exact_first_ar1 = FALSE, parallel = TRUE) {
    .Call(`_fmriAR_arma_whiten_inplace`, Y, X, phi, theta, run_starts, exact_first_ar1, parallel)
}

arma_whiten_void <- function(Y, X, phi, theta, run_starts, exact_first_ar1 = FALSE, parallel = TRUE) {
    invisible(.Call(`_fmriAR_arma_whiten_void`, Y, X, phi, theta, run_starts, exact_first_ar1, parallel))
}

